# Generated by Django 4.2.1 on 2023-05-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="patients", name="name",),
        migrations.AddField(
            model_name="patients",
            name="address",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patients",
            name="birthDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patients",
            name="family_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patients",
            name="gender",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="patients",
            name="given_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patients",
            name="mobile_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="patients",
            name="patient_id",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="patients",
            name="status",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="patients",
            name="work_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
