# Generated by Django 4.2.1 on 2023-05-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_patients_name_patients_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patients", old_name="birthDate", new_name="birth_date",
        ),
    ]
