# Generated by Django 4.2.1 on 2023-05-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_birthdate_patients_birth_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="patients", name="status",),
        migrations.AddField(
            model_name="patients",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
