# Generated by Django 4.2.1 on 2023-05-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_patients_status_patients_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patients",
            name="patient_id",
            field=models.CharField(default=None),
        ),
    ]
