# Generated by Django 4.2.1 on 2023-05-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_patients_patient_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="observations", name="name",),
        migrations.AddField(
            model_name="observations",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="observations",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="observations",
            name="display",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="observations",
            name="observation_id",
            field=models.CharField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name="observations",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="observations",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
