# Generated by Django 4.2.1 on 2023-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_observations_display_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observations",
            name="category",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="observations",
            name="code",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
